DROP DATABASE IF EXISTS pub;
CREATE DATABASE pub;

USE pub;

CREATE TABLE post_code (
pc_id VARCHAR(20),
PRIMARY KEY (pc_id)
) ENGINE=InnoDB;

create table pub (
pub_id VARCHAR(200),
pub_name VARCHAR(100) NOT NULL DEFAULT '',
locality VARCHAR(100) NOT NULL  DEFAULT '',
PRIMARY KEY (pub_id)
) ENGINE=InnoDB;

CREATE TABLE distance (
id INT NOT NULL AUTO_INCREMENT,
pc_id VARCHAR(20) NOT NULL,
pub_id VARCHAR(200) NOT NULL,
CONSTRAINT FK_PC FOREIGN KEY (pc_id) REFERENCES post_code(pc_id),
CONSTRAINT FK_PUB FOREIGN KEY (pub_id) REFERENCES pub(pub_id),
distance VARCHAR(100),
PRIMARY KEY (id)
) ENGINE=InnoDB;

